### ISSUE TITLE
Does this work for livestreams from YouTube and other .m3u8 livestreams? Or only video content? 

### ISSUE THREAD

**Issue by jeffward01** [dotnettools/SharpGrabber#33]

**Comment by JavidShoaei** [comment]
I haven't tried that yet, but I'm sure it's quite possible since m3u8 files are the same. The whole thing this library does is to parse the m3u8 files and get metadata about the URL and times of the TS files; and finally, concatenates those segments with a stream that also decrypts the TS files if encrypted.
