### ISSUE TITLE
Don't get pornhub urls

### ISSUE THREAD

**Issue by thisistorsten** [dotnettools/SharpGrabber#63]
Using this release I am not able to get pornhub video urls. The quality json is empty.

**Comment by javidsho** [comment]
Are you having problems with the desktop application?
Or is this issue related to development? If so, are you using `SharpGrabber.Adult` or `BlackWidow`?

**Comment by javidsho** [comment]
Just tested the desktop app and it's working just fine. Then I figure you're probably having issues with one of the libraries.

**Comment by hacksys1337** [comment]
Currently facing a similar issue, on DesktopApp and using SharpGrabber.Adult.
Desktop App Shows the following on any stream
![image](https://user-images.githubusercontent.com/9154593/165386407-91e55e13-4a08-4a0c-88d7-ac16bd7d714a.png)
Guessing due to Bitness, Ive also tried running x86 and x64 specifically in VS2019 via configuration 

SharpGrabber.Adult returns incorrect information when providing the data-video-vkey parsed from a view of videos. But browsing the the same uri in web displays a video result

Code for grabbing page
![PH2](https://user-images.githubusercontent.com/9154593/165388426-6a00590c-c76e-476d-aaa2-ddf43a1060a9.PNG)

Locals on variables and classes including streams and resulting titles.
![PH3](https://user-images.githubusercontent.com/9154593/165388436-f03a8dc4-35e3-4edf-9353-024a53ecef07.PNG)
![PH4](https://user-images.githubusercontent.com/9154593/165388452-93740022-60f4-4659-ad12-9c1dd00f3b27.PNG)

**Comment by javidsho** [comment]
@hacksys1337 You're using an old version of the app. The latest version grabs via BlackWidow without a problem. `SharpGrabber.Adult` though, is throwing exception.

**Comment by hacksys1337** [comment]
Does anything code wise need done Using the 4.5 version I get the same result on Desktop from Ran from Source and Tried from Compiled. Incorrect Video is returned containing the same result as SharpGrabber.Adult Implementation

![image](https://user-images.githubusercontent.com/9154593/165651922-cbb71b33-1c6d-4255-8c39-1fcdd1a681ae.png)

**Comment by javidsho** [comment]
The problem is fixed. Upgrade the `SharpGrabber.Adult` package.
