### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by bottleblue** [dotnettools/SharpGrabber#71]
It says I need .NET Core 3.1. I searched for it and got this https://dotnet.microsoft.com/en-us/download/dotnet/3.1
Which do I download? The SDK 3.1.417 or the ASP.NET Core Runtime 3.1.23?

Then I just need the SharpGrabber Desktop and it'll work?

Also the screenshot example you have of it grabbing the youtube video. It says Download and Convert. Is it re-encoding the file or directly downloading it? I don't want a conversion of the file I want a direct download. Is that what this program does?

**Comment by javidsho** [comment]
You'd need .NET Runtime to install just the necessary stuff to run the app. The SDK will also work but it's overkill.

As for your last question, YouTube usually provides complete media files (containing both audio and video channels) up to 480p. However, for 720p+ videos, YouTube provides separate audio-less video files. That's why for high-quality videos, the app will download the audio and video streams separately and then merge them into a single media file.

In the screen shot, the rest of the items are not shown. Those items contain low-quality choices that are directly downloadable.

**Comment by bottleblue** [comment]
Ok I understand. Thanks for the quick reply.

**Comment by javidsho** [comment]
No problem! I'm closing this issue then.
